### ISSUE TITLE
Config Enhancements: Basic Theming Variables

### ISSUE THREAD

**Issue by cycomachead** [berkeley-cdss/berkeley-class-site#48]
**Is your feature request related to a problem? Please describe.**
We should have a section to control a limited site of theme options, without requiring too much CSS re-writing or hacking.

**Describe the solution you'd like**
```yaml
theme_options:
  serif_headers: true|false
  course_logo_in_header: path/to/image
```

**Describe alternatives you've considered**
Making some better looking design choices.

**Additional context**
